### ISSUE TITLE
Hangs at the end of run when working with Aazure

### ISSUE THREAD

**Issue by SyRenity** [rickbergfalk/postgrator#5]
The module works well, however it hangs in the end of meta-data update when running against Azure SQL:

``` console
version of database is: 2
migrating up to 3
running XXXXXX
[ { version: 3,
    direction: 'do',
    action: 'do',
    filename: 'XXXXX
    name: XXXXXX
    md5: '890d87d2ea57bc266ab87f508a971e28',
    schemaVersionSQL: 'INSERT INTO schemaversion (version) VALUES (3);' } ]
```

On rerun, it hangs again with undefined:
``` console
version of database is: 3
migrating up to 3
undefined
````

**Comment by rickbergfalk** [comment]
Hi @SyRenity - 

When postgrator hangs is it not calling the callback you provide? In your last example (migrating from 3 to 3) you say it returns undefined. Is that something you are logging or is that logging done by postgrator?

**Comment by SyRenity** [comment]
Hi,

This is my migrator code:

``` javascript
postgrator.migrate('max', function (err, migrations) {
    if (err) {
        console.log(err)
    } else {
        console.log(migrations)
    }

    postgrator.endConnection(function () {
        // connection is closed, unless you are using SQL Server
    });
});
```

Unless I missing something, it should print out the result and exit?

**Comment by rickbergfalk** [comment]
Sorry for my delay in getting back to you @SyRenity. 

I think I know what's going on here. The SQL Server driver in use doesn't close when calling .endConnection(), which leaves your script open and running. It isn't doing anything at this point though, just sitting there with an open connection to SQL Server. 

I'll check, but I think the updated version of the SQL Server driver in use might close the connection now.

For the time being, it should be safe to do the following if you want to exit the script after running the migrations:

```js
postgrator.endConnection(function () {
  process.exit(); 
});
```

**Comment by rickbergfalk** [comment]
I published an updated version of postgrator - the sql server driver should close its db connection shortly after calling .endConnection().

This should resolve the behavior you are seeing

**Comment by SyRenity** [comment]
@rickbergfalk Thanks for the fix, when the updated NPM will be released?

I'm using meanwhile the above "endConnection" work-arround.

**Comment by rickbergfalk** [comment]
The fix has been published to npm as version 2.2.0. Hopefully it resolves what you are seeing.

Let me know how it works out :)

**Comment by SyRenity** [comment]
@rickbergfalk Still hangs :/, I'm using the process.exit for the meanwhile.
